# HTML_gen.py

from pathlib import Path

def generate_report(profile_w, profile_kwh, profile_pct, profile_pct_kwh):
    OUTPUT_BASE = Path("data") / "output"
    GRAPHS_DIR = OUTPUT_BASE / "Graphs"
    EXCEL_DIR = OUTPUT_BASE / "Excels"
    REPORT_PATH = OUTPUT_BASE / "report.html"
    REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)

    # Summary stats (W → Wh → kWh perspective)
    total_returned_energy_kWh = round(profile_kwh.sum(), 2)
    average_return_kWh = round(profile_kwh.mean(), 2)
    peak_time = profile_w.idxmax().strftime("%H:%M")
    peak_power_kW = round(profile_w.max(), 2)

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Rückspeisung Report (2023 + 2024)</title>
  <style>
    body {{ font-family: 'Segoe UI', sans-serif; margin: 2em; background: #fdfdfd; color: #222; }}
    h1, h2 {{ color: #004466; }}
    .stats {{ background: #eef; padding: 1em; border-left: 5px solid #007799; margin-bottom: 2em; }}
    img {{ max-width: 100%; margin: 1em 0; border: 1px solid #ccc; }}
    .download-link {{ margin: 0.5em 0; display: block; }}
    footer {{ font-size: 0.9em; margin-top: 4em; color: #777; }}
  </style>
</head>
<body>

  <h1>Rückspeisung Report (2023 + 2024)</h1>

  <div class="stats">
    <h2>Summary</h2>
    <ul>
      <li><strong>Total Rücklieferung:</strong> {total_returned_energy_kWh} kWh</li>
      <li><strong>Peak Rückspeisung:</strong> {peak_power_kW} kW at {peak_time}</li>
      <li><strong>Avg. Rückspeisung per 15-min:</strong> {average_return_kWh} kWh</li>
    </ul>
  </div>

  <h2>📈 Static Graphs</h2>
"""

    # Add static PNGs
    for img in sorted(GRAPHS_DIR.glob("*.png")):
        html += f"<h4>{img.stem.replace('_', ' ').title()}</h4>\n"
        html += f"<img src='Graphs/{img.name}' alt='{img.name}'>\n"

    # Excel files
    html += "<h2>Excel Downloads</h2>\n"
    for file in sorted(EXCEL_DIR.glob("*.xlsx")):
        html += f"<a class='download-link' href='Excels/{file.name}'>{file.name}</a>\n"

    html += """
  <footer>
    <p>Generated by Isak using Python</p>
  </footer>
</body>
</html>
"""

    REPORT_PATH.write_text(html, encoding="utf-8")
    print(f"Report generated: {REPORT_PATH.resolve()}")

